export default {
    "name": "",
    "fat": null,
    "calories": null,
    "proteins": null,
    "carbohydrates": null,
    "serving": null,
    "nutrients": {
        "Calcium": null,
        "Iron": null,
        "Potassium": null,
        "Magnesium": null,
        "Phosphorus": null,
        "Sodium": null,
        "Zinc": null,
        "Copper": null,
        "Manganese": null,
        "Selenium": null,
        "Vitamin C": null,
        "Vitamin B12": null,
        "Vitamin B1": null,
        "Vitamin B2": null,
        "Vitamin B3": null,
        "Vitamin B5": null,
        "Vitamin B6": null,
        "Vitamin B7": null,
        "Vitamin B9": null,
        "Choline": null,
        "Vitamin A": null,
        "Vitamin E": null,
        "Vitamin K": null,
        "Linoleic acid": null,
        "α-Linolenic acid": null,
        "Tryptophan": null,
        "Threonine": null,
        "Isoleucine": null,
        "Leucine": null,
        "Lysine": null,
        "Methionine": null,
        "Phenylalanine": null,
        "Valine": null,
        "Histidine": null
    }
};